import type { MangaExtensionConfig } from './types';

export const EXTENSION_CATALOG: MangaExtensionConfig[] = [
  // ── Core Unblocked & Fast Scanlation Sources ───────────────────────────────
  {
    id: 'asura',
    name: 'Asura Scans',
    baseUrl: 'https://asuracomic.net',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Premiere Korean manhwa releases (Solo Leveling, Mount Hua, Disaster-Class Hero)',
    enabled: true,
  },
  {
    id: 'mangadex',
    name: 'MangaDex',
    baseUrl: 'https://api.mangadex.org',
    engine: 'custom',
    category: 'manga',
    note: 'Global scanlation archive with over 100,000+ manga and manhwa titles',
    enabled: true,
  },
  {
    id: 'mangapill',
    name: 'MangaPill',
    baseUrl: 'https://mangapill.com',
    engine: 'custom',
    category: 'manga',
    note: 'Fast, reliable mainstream manga reader with zero Cloudflare bottlenecks',
    enabled: true,
  },
  {
    id: 'weebcentral',
    name: 'WeebCentral',
    baseUrl: 'https://weebcentral.com',
    engine: 'custom',
    category: 'manhwa',
    note: 'Massive Asian comic catalogue (50,000+ titles). Unblocked on Desktop app.',
    enabled: true,
    desktopOnly: true,
  },
  {
    id: 'flame',
    name: 'Flame Comics',
    baseUrl: 'https://flamecomics.com',
    engine: 'custom',
    category: 'manhwa',
    note: 'Korean action manhwa scanlation team. Unblocked on Desktop app.',
    enabled: true,
    desktopOnly: true,
  },

  // ── Dedicated Korean & Action Scanlation Teams (MangaStream / Themesia) ───
  {
    id: 'reaperscans',
    name: 'Reaper Scans',
    baseUrl: 'https://reaperscans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Top scanlation team for high fantasy & martial arts manhwa',
    enabled: true,
  },
  {
    id: 'radiantscans',
    name: 'Radiant Scans',
    baseUrl: 'https://radiantscans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'High-definition Korean manhwa and webtoon translations',
    enabled: true,
  },
  {
    id: 'voidscans',
    name: 'Hive Scans (Void)',
    baseUrl: 'https://hivescans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Fast action manhwa and dungeon progression releases',
    enabled: true,
  },
  {
    id: 'suryascans',
    name: 'Surya Scans',
    baseUrl: 'https://suryascans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Korean manhwa translation scans',
    enabled: true,
  },
  {
    id: 'nightscans',
    name: 'Night Comic',
    baseUrl: 'https://nightcomic.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Action, regression and levelling manhwa titles',
    enabled: true,
  },
  {
    id: 'drakescans',
    name: 'Drake Scans',
    baseUrl: 'https://drakescans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Action manhwa and murim martial arts series',
    enabled: true,
  },
  {
    id: 'zeroscans',
    name: 'Zero Scans',
    baseUrl: 'https://zeroscans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'High-quality Korean and Chinese comic releases',
    enabled: true,
  },
  {
    id: 'cosmicscans',
    name: 'Cosmic Scans',
    baseUrl: 'https://cosmicscans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Action and fantasy manhwa scans',
    enabled: true,
  },
  {
    id: 'immortalupdates',
    name: 'Immortal Updates',
    baseUrl: 'https://immortalupdates.com',
    engine: 'mangastream',
    category: 'manhua',
    note: 'Cultivation and martial arts manhua translations',
    enabled: true,
  },
  {
    id: 'resetscans',
    name: 'Reset Scans',
    baseUrl: 'https://reset-scans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Fantasy and reincarnation manhwa projects',
    enabled: true,
  },
  {
    id: 'luminous',
    name: 'Luminous Scans',
    baseUrl: 'https://luminousscans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'High-quality scanlations for Legend of the Northern Blade and action manhwa',
    enabled: true,
  },
  {
    id: 'astrascans',
    name: 'Astra Scans',
    baseUrl: 'https://astrascans.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Korean action and adventure scanlations',
    enabled: true,
  },
  {
    id: 'anxiousfansub',
    name: 'Anxious Fansub',
    baseUrl: 'https://anxiousfansub.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Webtoon and manhwa releases',
    enabled: true,
  },
  {
    id: 'realmscans',
    name: 'Rizz Comics',
    baseUrl: 'https://rizzcomic.com',
    engine: 'mangastream',
    category: 'manhwa',
    note: 'Popular Korean action manhwa and regression stories',
    enabled: true,
  },

  // ── Madara WordPress Scanlation & Webtoon Engines ──────────────────────────
  {
    id: 'manhuaplus',
    name: 'ManhuaPlus',
    baseUrl: 'https://manhuaplus.org',
    engine: 'madara',
    category: 'manhua',
    note: 'Leading cultivation and action series (Apotheosis, Tales of Demons and Gods)',
    enabled: true,
  },
  {
    id: 'toonily',
    name: 'Toonily',
    baseUrl: 'https://toonily.com',
    engine: 'madara',
    category: 'webtoon',
    note: 'Large manhwa and full-colour Korean webtoon library',
    enabled: true,
  },
  {
    id: 'mangatx',
    name: 'MangaTx',
    baseUrl: 'https://mangatx.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Daily updated Korean manhwa and Chinese manhua',
    enabled: true,
  },
  {
    id: 'mangaclash',
    name: 'MangaClash',
    baseUrl: 'https://mangaclash.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Broad webtoon and scanlation aggregator',
    enabled: true,
  },
  {
    id: '1stkissmanga',
    name: '1stKissManga',
    baseUrl: 'https://1stkissmanga.me',
    engine: 'madara',
    category: 'manhwa',
    note: 'Romance, fantasy and action manhwa catalogue',
    enabled: true,
  },
  {
    id: 'mangachill',
    name: 'MangaChill',
    baseUrl: 'https://mangachill.net',
    engine: 'madara',
    category: 'webtoon',
    note: 'Webtoons, romance and fantasy manhwa series',
    enabled: true,
  },
  {
    id: 'kunmanga',
    name: 'KunManga',
    baseUrl: 'https://kunmanga.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Extensive webtoon collection with daily updates',
    enabled: true,
  },
  {
    id: 'webtoonxyz',
    name: 'WebtoonXYZ',
    baseUrl: 'https://www.webtoon.xyz',
    engine: 'madara',
    category: 'webtoon',
    note: 'Dedicated Korean webtoon and vertical scroll reader',
    enabled: true,
  },
  {
    id: 'readmanhwa',
    name: 'ReadManhwa',
    baseUrl: 'https://readmanhwa.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Korean manhwa exclusive library',
    enabled: true,
  },
  {
    id: 'topmanhua',
    name: 'TopManhua',
    baseUrl: 'https://topmanhua.com',
    engine: 'madara',
    category: 'manhua',
    note: 'Chinese martial arts and levelling manhua',
    enabled: true,
  },
  {
    id: 'mangakomi',
    name: 'MangaKomi',
    baseUrl: 'https://mangakomi.io',
    engine: 'madara',
    category: 'manhwa',
    note: 'Manhwa, manhua and Japanese manga releases',
    enabled: true,
  },
  {
    id: 'mangabob',
    name: 'MangaBob',
    baseUrl: 'https://mangabob.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Action, comedy, and fantasy manhwa collection',
    enabled: true,
  },
  {
    id: 'mangagreat',
    name: 'MangaGreat',
    baseUrl: 'https://mangagreat.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Webtoon updates and fast releases',
    enabled: true,
  },
  {
    id: 's2manga',
    name: 'S2Manga',
    baseUrl: 'https://s2manga.com',
    engine: 'madara',
    category: 'webtoon',
    note: 'Webtoon releases with high image resolution',
    enabled: true,
  },
  {
    id: 'hiperdex',
    name: 'Hiperdex',
    baseUrl: 'https://hiperdex.com',
    engine: 'madara',
    category: 'webtoon',
    note: 'Modern webtoons and full-colour series',
    enabled: true,
  },
  {
    id: 'manhwatop',
    name: 'ManhwaTop',
    baseUrl: 'https://manhwatop.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Top trending Korean manhwa updates',
    enabled: true,
  },
  {
    id: 'mangademon',
    name: 'MangaDemon',
    baseUrl: 'https://mangademon.org',
    engine: 'madara',
    category: 'manhwa',
    note: 'Dark fantasy and action manhwa catalogue',
    enabled: true,
  },
  {
    id: 'mangacult',
    name: 'MangaCult',
    baseUrl: 'https://mangacult.org',
    engine: 'madara',
    category: 'manga',
    note: 'Manga and manhwa chapter releases',
    enabled: true,
  },
  {
    id: 'mangaweebs',
    name: 'MangaWeebs',
    baseUrl: 'https://mangaweebs.in',
    engine: 'madara',
    category: 'manga',
    note: 'Manga scanlations with clean layouts',
    enabled: true,
  },
  {
    id: 'mangaeffect',
    name: 'MangaEffect',
    baseUrl: 'https://mangaeffect.com',
    engine: 'madara',
    category: 'manhwa',
    note: 'Action and fantasy manhwa collection',
    enabled: true,
  },

  // ── MangaBox Large Catalogs (MangaKakalot / Manganato) ─────────────────────
  {
    id: 'mangakakalot',
    name: 'MangaKakalot',
    baseUrl: 'https://mangakakalot.com',
    engine: 'mangabox',
    category: 'manga',
    note: 'One of the largest, longest-standing manga databases online',
    enabled: true,
  },
  {
    id: 'manganato',
    name: 'Manganato',
    baseUrl: 'https://manganato.com',
    engine: 'mangabox',
    category: 'manga',
    note: 'Massive library of completed and releasing manga and manhwa',
    enabled: true,
  },
  {
    id: 'chapmanganato',
    name: 'ChapManganato',
    baseUrl: 'https://chapmanganato.to',
    engine: 'mangabox',
    category: 'manga',
    note: 'Direct fast chapter mirror for Manganato',
    enabled: true,
  },
  {
    id: 'readmanganato',
    name: 'ReadManganato',
    baseUrl: 'https://readmanganato.com',
    engine: 'mangabox',
    category: 'manga',
    note: 'Alternative fast mirror for Manganato series',
    enabled: true,
  },

  // ── Custom Aggregators & Classic Archives ──────────────────────────────────
  {
    id: 'batoto',
    name: 'Bato.to',
    baseUrl: 'https://bato.to',
    engine: 'custom',
    category: 'webtoon',
    note: 'Huge community library with high-res scans, manhwa and webtoons',
    enabled: true,
  },
  {
    id: 'mangafire',
    name: 'MangaFire',
    baseUrl: 'https://mangafire.to',
    engine: 'custom',
    category: 'manga',
    note: 'Modern manga and manhwa reader with multi-language scans',
    enabled: true,
  },
  {
    id: 'tcbscans',
    name: 'TCB Scans',
    baseUrl: 'https://tcbscans.me',
    engine: 'custom',
    category: 'manga',
    note: 'Industry standard for Weekly Shonen Jump (One Piece, JJK)',
    enabled: true,
  },
  {
    id: 'mangahere',
    name: 'MangaHere',
    baseUrl: 'https://www.mangahere.cc',
    engine: 'custom',
    category: 'manga',
    note: 'Classic manga archive with extensive completed titles',
    enabled: true,
  },
  {
    id: 'fanfox',
    name: 'FanFox (MangaFox)',
    baseUrl: 'https://fanfox.net',
    engine: 'custom',
    category: 'manga',
    note: 'Deep retro and modern manga catalogue',
    enabled: true,
  },
  {
    id: 'mangareader',
    name: 'MangaReader',
    baseUrl: 'https://mangareader.to',
    engine: 'custom',
    category: 'manga',
    note: 'Fast streaming manga reader',
    enabled: true,
  },
  {
    id: 'kissmanga',
    name: 'KissManga',
    baseUrl: 'https://kissmanga.org',
    engine: 'custom',
    category: 'manga',
    note: 'Large index of ongoing and completed series',
    enabled: true,
  },
  {
    id: 'mangafreak',
    name: 'MangaFreak',
    baseUrl: 'https://mangafreak.net',
    engine: 'custom',
    category: 'manga',
    note: 'Direct chapter downloads and archive reader',
    enabled: true,
  },
  {
    id: 'mangapark',
    name: 'MangaPark',
    baseUrl: 'https://mangapark.net',
    engine: 'custom',
    category: 'manga',
    note: 'Multi-version scanlation aggregator with reader comments',
    enabled: true,
  },
  {
    id: 'mangasee',
    name: 'MangaSee',
    baseUrl: 'https://mangasee123.com',
    engine: 'custom',
    category: 'manga',
    note: 'Official rip qualities for popular weekly manga',
    enabled: true,
  },
  {
    id: 'mangalife',
    name: 'MangaLife',
    baseUrl: 'https://mangalife.us',
    engine: 'custom',
    category: 'manga',
    note: 'Fast mirror for high-definition manga releases',
    enabled: true,
  },
  {
    id: 'comick',
    name: 'Comick',
    baseUrl: 'https://comick.io',
    engine: 'custom',
    category: 'manhwa',
    note: 'Clean manhwa and manga reader with comprehensive group tracking',
    enabled: true,
  },
  {
    id: 'mangaowl',
    name: 'MangaOwl',
    baseUrl: 'https://mangaowl.io',
    engine: 'custom',
    category: 'webtoon',
    note: 'Webtoon, romance and action manhwa archive',
    enabled: true,
  },
];
